### ISSUE TITLE
`nsc generate nkey` outputs good response to stderr rather than stdout

### ISSUE THREAD

**Issue by kimjarvis** [nats-io/nsc#580]
`nsc generate nkey` outputs a good response to stderr, rather than stdout, which is unexpected.      

```bash
root@instance:/# nsc generate nkey -a --store 2> e
root@instance:/# nsc generate nkey -a --store
AALS5NG2EJCJGCBTCRRH4PJO2R2UFHVAAIPLZEI5OPHHGW5T67DFNJRY
account key stored /root/.local/share/nats/nsc/keys/keys/A/AL/AALS5NG2EJCJGCBTCRRH4PJO2R2UFHVAAIPLZEI5OPHHGW5T67DFNJRY.nk
```

In particular, I would expect the following ansible to work.  But, to make it work i had to change stdout to stderr.

```yaml
    - name: Generate account signing key
      ansible.builtin.shell: >-
        nsc generate nkey -a --store
        {{ client_config }}
      register: result

    - name: Get the client account signing key 
      ansible.builtin.set_fact: client_account_signing_key="{{result.stdout_lines[0]}}"
```
